### ISSUE TITLE
don't put the query logic in the view

### ISSUE THREAD

**Issue by ahmedakef** [En14c/AMA#3]
https://github.com/En14c/AMA/blob/7cef56cc8cf5c229d8db4f4e7d29e9cbce669a04/app/main/views.py#L23

following separation of concerns pattern, it is better to call another class to get the user answered question you can use "get_answered_questions(self)" method from the model after editing it to accept the a limit argument.
the result will make the view code elegant and can be understood without going into query details

**Comment by En14c** [comment]
i started following this pattern as of commit **45b5872**
